In [4]:
# Exercise 1

# MonthNames.py
# Program to convert month number to month name

# Get input from user
month_num = int(input("Enter the month: "))

# Dictionary to store month numbers and names
months = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

# Check if input is valid and print result
if month_num in months:
    print(f"Month {month_num} is {months[month_num]}")
else:
    print("Invalid month number. Please enter a number between 1 and 12.")

Enter the month: 5
Month 5 is May

In [6]:
# Exercise 2

def calculate_ticket_price(age):
    full_price = 6.00
    if age < 16:
        return full_price / 2
    elif age >= 60:
        return full_price / 3
    else:
        return full_price

# Get user input
try:
    age = int(input("Enter your age: "))
    ticket_price = calculate_ticket_price(age)
    print(f"Your ticket costs £{ticket_price:.2f}")
except ValueError:
    print("Invalid input. Please enter a valid age.")

Enter your age: 16
Your ticket costs £6.00

In [7]:
# Exercise 3

# BodyMassIndex.py
# Program to calculate BMI and determine weight status

# Get input from user
weight = float(input("Enter your weight in (kg): "))
height = float(input("Enter your height in (m): "))

# Calculate BMI
bmi = weight / (height ** 2)

# Determine weight status
if bmi < 18.5:
    category = "underweight"
elif bmi < 25:
    category = "normal"
elif bmi < 30:
    category = "overweight"
else:
    category = "obese"

# Print results
print(f"Your BMI is: {bmi:.2f}")
print(f'You are in the "{category}" range.')

Enter your weight in (kg): 45
Enter your height in (m): 147
Your BMI is: 0.00
You are in the "underweight" range.

In [8]:
# Excercise 4

# Get three numbers from user
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

# Find the greatest number
greatest = max(num1, num2, num3)

print(f"The greatest number is: {greatest}")

Enter first number: 1
Enter second number: 2
Enter third number: 3
The greatest number is: 3.0

In [9]:
# Excercise 5

# Get number from user
num = int(input("Enter a number: "))

# Calculate factorial
factorial = 1
for i in range(1, num + 1):
    factorial *= i

print(f"The factorial of {num} is {factorial}")

Enter a number: 10
The factorial of 10 is 3628800

In [10]:
# Excercise 6

# Get number from user
num = int(input("Enter a number: "))

# Reverse the number
reversed_num = 0
while num > 0:
    digit = num % 10
    reversed_num = (reversed_num * 10) + digit
    num = num // 10

print(f"Reversed number is: {reversed_num}")

Enter a number: 2
Reversed number is: 2

In [11]:
# Excercise 7

# Get number from user
num = int(input("Enter a number: "))
limit = int(input("Enter limit for multiples: "))

# Print multiples
print(f"Multiples of {num} up to {limit}:")
for i in range(1, limit + 1):
    print(num * i, end=" ")
print()  # For new line at end

Enter a number: 10
Enter limit for multiples: 8
Multiples of 10 up to 8:
10 20 30 40 50 60 70 80

In [13]:
# Excercise 8
while True:
    user_input = input(":")
    if user_input.lower() == "done":
        print("Done")
        break
    print(user_input)

:done
Done

In [14]:
# Excercise 9

for i in range(1, 11):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz

In [15]:
# Excercise 10

for i in range(5, 0, -1):
    for j in range(i, 0, -1):
        print(j, end=" ")
    print()  # For new line after each row

5 4 3 2 1
4 3 2 1
3 2 1
2 1
1