In [2]:
# Q1: Create a list of 5 random numbers and print the list
import random
random_list = [random.randint(1, 100) for _ in range(5)]
print("Original List:", random_list)

Original List: [99, 59, 89, 57, 36]

In [3]:

# Q2: Insert 3 new values to the list and print the updated list
random_list.extend([200, 300, 400])
print("Updated List:", random_list)

Updated List: [99, 59, 89, 57, 36, 200, 300, 400]

In [4]:

# Q3: Use a for loop to print each element in the list
print("List Elements:")
for num in random_list:
    print(num)

List Elements:
99
59
89
57
36
200
300
400

In [5]:
# Q1: Create a dictionary with given keys and values
person = {'name': 'John', 'age': 25, 'address': 'New York'}
print("Dictionary:", person)

Dictionary: {'name': 'John', 'age': 25, 'address': 'New York'}

In [6]:
# Q2: Add a new key-value pair ('phone', '1234567890') to the dictionary
person['phone'] = '1234567890'
print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'John', 'age': 25, 'address': 'New York', 'phone': '1234567890'}

In [7]:
# Q1: Create a set with values 1, 2, 3, 4, and 5
num_set = {1, 2, 3, 4, 5}
print("Original Set:", num_set)

Original Set: {1, 2, 3, 4, 5}

In [8]:
# Q2: Add the value 6 to the set
num_set.add(6)
print("Updated Set:", num_set)

Updated Set: {1, 2, 3, 4, 5, 6}

In [9]:
# Q3: Remove the value 3 from the set
num_set.discard(3)  # discard avoids error if the value is not present
print("Set after removing 3:", num_set)

Set after removing 3: {1, 2, 4, 5, 6}

In [10]:
# Q1: Create a tuple with values 1, 2, 3, and 4
num_tuple = (1, 2, 3, 4)
print("Tuple:", num_tuple)

Tuple: (1, 2, 3, 4)

In [12]:
# Q2: Print the length of the tuple
print("Length of Tuple:", len(num_tuple))

Length of Tuple: 4